# Include settings for your email server/mailbox below (you probably only need to edit the "production" settings).
# Settings here are used to generate your crontab configuration when running the "whenever" command.
---
development:

test:

production:
  pop:
    host: 
    username: 
    password: 
  smtp:
    address: localhost
    domain: imarina.net
    # probably not needed...
    #port: 25
    #authentication: login
    #user_name: user_for_smtp_auth@example.com
    #password: password_for_smtp_auth
